version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
  pre_build:
    commands:
    - mvn install
    - echo Pre-build completed on 'data'
  build:
    commands:
    - echo Build completed on date
    - mvn compile
    - mvn test
  post_build:
    commands:
    - echo Build completed on date
    - mvn package
    - cp target/*.war Adwaa.war
artifacts:
  files:
  - Adwaa.war
